version: '3'
services:

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: karpovich
      POSTGRES_USER: postgres
      POSTGRES_DB: messenger_rest
    volumes:
      - ./tmp/pg-db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:$PG_EXT_PORT:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:$REDIS_EXT_PORT:6379"
    volumes:
      - ./tmp/redis-db:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean spring-boot:run
    ports:
      - "127.0.0.1:$APP_PORT:8080"
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis
